version: 1.1.0-b{build}
clone_folder: c:\projects\poc
init:
  # Checking that DEP is enabled
  - ps: Write-Host "Initializing virtual machine ..."
  - ps: git --version
  - ps: $env:Path = $env:Path.Replace("Python27", "Python35-x64")

install:
  - ps: Write-Host "Installing requirements..."
  - ps: python --version
  - ps: python -m pip install pip --upgrade
  - ps: python -m pip install -r .\requirements.txt
  - ps: python -m pip list --format=columns
  - ps: Write-Host "Configuring PoC..."
  - ps: cp .\tools\AppVeyor\config.private.ini .\py\
  - ps: cp .\tools\AppVeyor\my_project.vhdl .\tb\common\
  - ps: .\poc.ps1

build: off

build_script:
  - ps: Write-Host "Testing query interface..."
  - ps: .\poc.ps1 query INSTALL.PoC:InstallationDirectory
  - ps: Write-Host "Testing information interface..."
  - ps: .\poc.ps1 list-testbench
  - ps: .\poc.ps1 list-netlist
  - ps: Write-Host "Testing simulators..."
  - ps: .\poc.ps1 --dryrun ghdl PoC.arith.prng --analyze --elaborate
  - ps: Write-Host "Testing synthesizers..."
  - ps: .\poc.ps1 --dryrun quartus PoC.arith.prng --board=DE4
  - ps: .\poc.ps1 --dryrun lse PoC.arith.prng --board=ECP5Versa
  - ps: .\poc.ps1 --dryrun xst PoC.arith.prng --board=KC705
  - ps: .\poc.ps1 --dryrun vivado PoC.arith.prng --board=KC705
  - ps: Write-Host "Testing core generators..."
  - ps: .\poc.ps1 --dryrun coregen PoC.xil.mig.Atlys_1x128 --board=Atlys
