language: python
matrix:
  include:
    - env: CONFIG="Trusty,Python3.6,libgnat-4.8,grc-1.11"
      os: linux
      sudo: required
      dist: trusty
      python: "3.6"
      before_install:
        - sudo apt-get update
        - sudo apt-get install -y libgnat-4.8
        - sudo ./tools/Travis-CI/grc.setup.sh
    - env: CONFIG="Precise,Python3.6,gnat-5"
      os: linux
      python: "3.6"
      addons:
        apt:
          packages:
            - gnat-5
  allow_failures:
    - env: CONFIG="Precise,Python3.6,gnat-5"
install:
  - pip3 install -r tools/Travis-CI/requirements.txt
before_script:
  - ./tools/Travis-CI/ghdl.setup.sh
  - ./tools/Travis-CI/poc.setup.sh
script:
  - ./tools/Travis-CI/poc.dryrun.sh
  - ./tools/Travis-CI/poc.run.sh "PoC.*"
